package com.lioigor22.model.dtos;

import java.io.Serializable;

import javax.persistence.Embedded;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

import org.springframework.context.annotation.Profile;

import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
@Profile("json")
public class UserDto implements Serializable {

	private static final long serialVersionUID = 1L;

	// An autogenerated id (unique for each user in the db)
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private long id;

	private String username;

	private String password;

	private String fullName;

	@Embedded
	@JsonProperty("Role")
	private EmbeddedRoleDto embeddedRoleDto;

	public UserDto() {

	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullName() {
		return fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public EmbeddedRoleDto getRoleDto() {
		return embeddedRoleDto;
	}

	public void setRoleDto(EmbeddedRoleDto userRoleDto) {
		this.embeddedRoleDto = userRoleDto;
	}

	@Override
	public String toString() {
		return "UserDto [id=" + id + ", username=" + username + ", password=" + password + ", fullName=" + fullName + ", userRoleDto=" + embeddedRoleDto + "]";
	}

}
